[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Jeffrey's Doc"
authors = [{name = "Jeffrey", email = "ren_jeffrey@outlook.com"}]
dynamic = ["version", "description"]
